const router = require('express').Router();
const { equipoController, validaciones } = require('../controllers/equipoController');
const { auth } = require('../middlewares/auth');
const { authorize } = require('../middlewares/role');
const { validate } = require('../middlewares/validate');
const { mantenimientoController, validaciones: mantenimientoValidaciones } = require('../controllers/mantenimientoController');
const { movimientoController, validaciones: movimientoValidaciones } = require('../controllers/movimientoController');
const { audit } = require('../middlewares/audit');
const lectores = ['admin', 'ingeniero_biomedico', 'tecnico', 'usuario_clinico'];
router.use(auth, audit('equipos'));
router.get('/', authorize(...lectores), validate(validaciones.listar), equipoController.listar);
router.get('/:id/mantenimientos', authorize('admin', 'ingeniero_biomedico', 'tecnico'), validate(mantenimientoValidaciones.obtener), mantenimientoController.historial);
router.get('/:id/movimientos', authorize('admin', 'ingeniero_biomedico', 'tecnico'), validate(movimientoValidaciones.obtener), movimientoController.historial);
router.get('/:id', authorize(...lectores), validate(validaciones.obtener), equipoController.obtener);
router.post('/', authorize('admin', 'ingeniero_biomedico'), validate(validaciones.crear), equipoController.crear);
router.put('/:id', authorize('admin', 'ingeniero_biomedico'), validate(validaciones.actualizar), equipoController.actualizar);
router.patch('/:id/estado', authorize('admin', 'ingeniero_biomedico'), validate(validaciones.cambiarEstado), equipoController.cambiarEstado);
router.delete('/:id', authorize('admin'), validate(validaciones.eliminar), equipoController.eliminar);
module.exports = router;
