const {fallaRepository}=require('../repositories/fallaRepository');const {equipoRepository}=require('../repositories/equipoRepository');const {usuarioRepository}=require('../repositories/usuarioRepository');const {notificacionRepository}=require('../repositories/notificacionRepository');const {AppError}=require('../utils/appError');
const fallaService={
 listar:(f)=>fallaRepository.findAll(f),
 async obtener(id,user){const r=await fallaRepository.findById(id);if(!r)throw new AppError('Reporte de falla no encontrado',404);if(user&&user.roles.length===1&&user.roles.includes('usuario_clinico')&&r.reportado_por!==user.id)throw new AppError('No tienes permiso para consultar este reporte',403);return r},
 async crear(data,userId){const e=await equipoRepository.findById(data.equipo_id);if(!e?.estaActivo())throw new AppError('Equipo no válido',400);const r=await fallaRepository.create({...data,reportado_por:userId});if(r.esCritica()){await notificacionRepository.createForRoles(['admin','ingeniero_biomedico','tecnico'],{tipo:'falla_critica',titulo:'Falla crítica reportada',mensaje:`Se reportó una falla crítica en ${e.nombre}`,referencia_id:r.id})}return r},
 async actualizar(id,data){const a=await this.obtener(id);if(a.estaFinalizada())throw new AppError('El reporte está finalizado',409);return fallaRepository.update(id,data)},
 async asignar(id,tecnicoId){const a=await this.obtener(id);if(a.estaFinalizada())throw new AppError('El reporte está finalizado',409);const u=await usuarioRepository.findById(tecnicoId);if(!u?.estaActivo()||!u.roles.some(r=>['tecnico','ingeniero_biomedico','admin'].includes(r)))throw new AppError('Técnico no válido',400);return fallaRepository.update(id,{tecnico_asignado_id:tecnicoId,estado:a.estado==='reportada'?'revisada':a.estado})},
 async prioridad(id,prioridad){await this.obtener(id);return fallaRepository.update(id,{prioridad})},
 async estado(id,estado){const a=await this.obtener(id);if(a.estado==='cerrada')throw new AppError('La falla ya está cerrada',409);const r=await fallaRepository.update(id,{estado});if(estado==='en_reparacion')await equipoRepository.setEstado(a.equipo_id,'en_reparacion');if(['resuelta','rechazada'].includes(estado))await equipoRepository.setEstado(a.equipo_id,'operativo');return r},
 async cerrar(id,{solucion}){const a=await this.obtener(id);if(!a.puedeCerrarse(solucion))throw new AppError('La falla ya está cerrada o no tiene solución',409);const r=await fallaRepository.update(id,{estado:'cerrada',solucion,fecha_cierre:new Date()});await equipoRepository.setEstado(a.equipo_id,'operativo');return r},
};module.exports={fallaService};
