const swaggerJsDoc=require('swagger-jsdoc');
const examples={
 Auth:{email:'usuario@clinica.com',password:'ClaveSegura123'},
 Equipos:{codigo_interno:'EQ-001',nombre:'Monitor de signos vitales',numero_serie:'SN-001',estado:'operativo',nivel_riesgo:'alto'},
 Mantenimientos:{equipo_id:'00000000-0000-4000-8000-000000000000',tipo:'preventivo',fecha_programada:'2026-08-15',descripcion_trabajo:'Revisión general'},
 Calibraciones:{equipo_id:'00000000-0000-4000-8000-000000000000',fecha:'2026-07-17',resultado:'aprobado',proxima_fecha:'2027-07-17'},
 Repuestos:{nombre:'Sensor de oxígeno',codigo:'REP-001',cantidad_disponible:10,stock_minimo:2,precio:25.5},
 Fallas:{equipo_id:'00000000-0000-4000-8000-000000000000',descripcion:'El equipo no enciende',prioridad:'alta'},
 Movimientos:{equipo_id:'00000000-0000-4000-8000-000000000000',tipo:'prestamo',ubicacion_destino_id:'00000000-0000-4000-8000-000000000000',fecha_prevista_devolucion:'2026-07-20T18:00:00Z',motivo:'Apoyo temporal'},
};
const paths={};
const add=(method,path,tag,summary,{publicRoute=false,body=false}={})=>{
 const openPath=path.replace(/:([a-z_]+)/g,'{$1}');
 const parameters=[...path.matchAll(/:([a-z_]+)/g)].map(m=>({name:m[1],in:'path',required:true,schema:{type:'string',format:'uuid'}}));
 paths[openPath]??={};paths[openPath][method.toLowerCase()]={tags:[tag],summary,security:publicRoute?[]:[{bearerAuth:[]}],parameters,responses:{200:{$ref:'#/components/responses/Success'},201:{$ref:'#/components/responses/Created'},401:{$ref:'#/components/responses/Unauthorized'},403:{$ref:'#/components/responses/Forbidden'},422:{$ref:'#/components/responses/ValidationError'}}};
 if(body)paths[openPath][method.toLowerCase()].requestBody={required:true,content:{'application/json':{schema:{type:'object'},example:examples[tag]||{}}}};
};
[
 ['post','/api/auth/register','Auth','Registrar usuario',{publicRoute:true,body:true}],['post','/api/auth/login','Auth','Iniciar sesión',{publicRoute:true,body:true}],['get','/api/auth/profile','Auth','Consultar perfil'],['post','/api/auth/change-password','Auth','Cambiar contraseña',{body:true}],
 ['get','/api/usuarios','Usuarios','Listar usuarios'],['get','/api/usuarios/:id','Usuarios','Consultar usuario'],['post','/api/usuarios','Usuarios','Crear usuario',{body:true}],['put','/api/usuarios/:id','Usuarios','Actualizar usuario',{body:true}],['patch','/api/usuarios/:id/estado','Usuarios','Cambiar estado',{body:true}],
 ['get','/api/roles','Roles','Listar roles'],['get','/api/roles/:id','Roles','Consultar rol'],['post','/api/roles','Roles','Crear rol',{body:true}],['put','/api/roles/:id','Roles','Actualizar rol',{body:true}],['patch','/api/roles/:id/estado','Roles','Cambiar estado',{body:true}],['delete','/api/roles/:id','Roles','Desactivar rol'],
 ['get','/api/equipos','Equipos','Listar y filtrar equipos'],['get','/api/equipos/:id','Equipos','Consultar equipo'],['post','/api/equipos','Equipos','Registrar equipo',{body:true}],['put','/api/equipos/:id','Equipos','Actualizar equipo',{body:true}],['patch','/api/equipos/:id/estado','Equipos','Cambiar estado',{body:true}],['delete','/api/equipos/:id','Equipos','Dar de baja'],['get','/api/equipos/:id/mantenimientos','Equipos','Historial de mantenimientos'],['get','/api/equipos/:id/movimientos','Equipos','Historial de movimientos'],
 ['get','/api/categorias','Categorías','Listar categorías'],['get','/api/categorias/:id','Categorías','Consultar categoría'],['post','/api/categorias','Categorías','Crear categoría',{body:true}],['put','/api/categorias/:id','Categorías','Actualizar categoría',{body:true}],['patch','/api/categorias/:id/estado','Categorías','Cambiar estado',{body:true}],
 ['get','/api/ubicaciones','Ubicaciones','Listar ubicaciones'],['get','/api/ubicaciones/:id','Ubicaciones','Consultar ubicación'],['post','/api/ubicaciones','Ubicaciones','Crear ubicación',{body:true}],['put','/api/ubicaciones/:id','Ubicaciones','Actualizar ubicación',{body:true}],['patch','/api/ubicaciones/:id/estado','Ubicaciones','Cambiar estado',{body:true}],
 ['get','/api/proveedores','Proveedores','Listar proveedores'],['get','/api/proveedores/:id','Proveedores','Consultar proveedor'],['post','/api/proveedores','Proveedores','Crear proveedor',{body:true}],['put','/api/proveedores/:id','Proveedores','Actualizar proveedor',{body:true}],['patch','/api/proveedores/:id/estado','Proveedores','Cambiar estado',{body:true}],['get','/api/proveedores/:id/equipos','Proveedores','Equipos suministrados'],
 ['get','/api/mantenimientos','Mantenimientos','Listar mantenimientos'],['get','/api/mantenimientos/proximos','Mantenimientos','Consultar próximos'],['get','/api/mantenimientos/vencidos','Mantenimientos','Consultar vencidos'],['get','/api/mantenimientos/:id','Mantenimientos','Consultar mantenimiento'],['post','/api/mantenimientos','Mantenimientos','Programar mantenimiento',{body:true}],['put','/api/mantenimientos/:id','Mantenimientos','Actualizar mantenimiento',{body:true}],['patch','/api/mantenimientos/:id/estado','Mantenimientos','Cambiar estado',{body:true}],['post','/api/mantenimientos/:id/repuestos','Mantenimientos','Consumir repuesto',{body:true}],
 ['get','/api/calibraciones','Calibraciones','Listar calibraciones'],['get','/api/calibraciones/proximas','Calibraciones','Consultar próximas'],['get','/api/calibraciones/vencidas','Calibraciones','Consultar vencidas'],['get','/api/calibraciones/:id','Calibraciones','Consultar calibración'],['post','/api/calibraciones','Calibraciones','Registrar calibración',{body:true}],['put','/api/calibraciones/:id','Calibraciones','Actualizar calibración',{body:true}],
 ['get','/api/repuestos','Repuestos','Consultar inventario'],['get','/api/repuestos/bajo-stock','Repuestos','Consultar bajo stock'],['get','/api/repuestos/:id','Repuestos','Consultar repuesto'],['post','/api/repuestos','Repuestos','Registrar repuesto',{body:true}],['put','/api/repuestos/:id','Repuestos','Actualizar repuesto',{body:true}],['patch','/api/repuestos/:id/stock','Repuestos','Registrar movimiento de stock',{body:true}],['patch','/api/repuestos/:id/estado','Repuestos','Cambiar estado',{body:true}],
 ['get','/api/fallas','Fallas','Listar fallas'],['get','/api/fallas/:id','Fallas','Consultar falla'],['post','/api/fallas','Fallas','Reportar falla',{body:true}],['put','/api/fallas/:id','Fallas','Actualizar reporte',{body:true}],['patch','/api/fallas/:id/asignar','Fallas','Asignar técnico',{body:true}],['patch','/api/fallas/:id/prioridad','Fallas','Cambiar prioridad',{body:true}],['patch','/api/fallas/:id/estado','Fallas','Cambiar estado',{body:true}],['patch','/api/fallas/:id/cerrar','Fallas','Cerrar falla',{body:true}],
 ['get','/api/movimientos','Movimientos','Listar movimientos'],['get','/api/movimientos/prestados','Movimientos','Consultar equipos prestados'],['get','/api/movimientos/:id','Movimientos','Consultar movimiento'],['post','/api/movimientos','Movimientos','Registrar traslado o préstamo',{body:true}],['patch','/api/movimientos/:id/devolver','Movimientos','Registrar devolución'],
 ['get','/api/dashboard/resumen','Dashboard','Resumen general'],['get','/api/dashboard/equipos-por-estado','Dashboard','Equipos por estado'],['get','/api/dashboard/equipos-por-area','Dashboard','Equipos por área'],['get','/api/dashboard/equipos-por-categoria','Dashboard','Equipos por categoría'],['get','/api/dashboard/equipos-por-riesgo','Dashboard','Equipos por riesgo'],['get','/api/dashboard/fallas','Dashboard','Indicadores de fallas'],['get','/api/dashboard/mantenimientos','Dashboard','Indicadores de mantenimientos'],['get','/api/dashboard/costos','Dashboard','Costos de mantenimiento'],
 ['get','/api/auditorias','Auditoría','Consultar auditoría'],['get','/api/notificaciones','Notificaciones','Listar notificaciones'],['patch','/api/notificaciones/:id/leida','Notificaciones','Marcar como leída'],
].forEach(args=>add(...args));

module.exports=swaggerJsDoc({definition:{openapi:'3.0.3',info:{title:'MedEquip API',version:'1.0.0',description:'API REST para la gestión integral de equipos médicos'},servers:[{url:'http://localhost:3000',description:'Desarrollo local'}],components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT'}},schemas:{Success:{type:'object',properties:{success:{type:'boolean',example:true},message:{type:'string'},data:{}}},Error:{type:'object',properties:{success:{type:'boolean',example:false},message:{type:'string'},errors:{type:'array',items:{type:'object'}}}}},responses:{Success:{description:'Operación correcta',content:{'application/json':{schema:{$ref:'#/components/schemas/Success'}}}},Created:{description:'Recurso creado',content:{'application/json':{schema:{$ref:'#/components/schemas/Success'}}}},Unauthorized:{description:'No autenticado',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}},Forbidden:{description:'Sin permisos',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}},ValidationError:{description:'Error de validación',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}}},paths},apis:[]});
