const pool=require('../config/database');
const dashboardRepository={
 async resumen(){const r=await pool.query(`SELECT (SELECT COUNT(*) FROM equipos WHERE activo=TRUE)::int total_equipos,(SELECT COUNT(*) FROM equipos WHERE activo=TRUE AND estado='operativo')::int equipos_operativos,(SELECT COUNT(*) FROM equipos WHERE activo=TRUE AND estado='en_mantenimiento')::int equipos_mantenimiento,(SELECT COUNT(*) FROM equipos WHERE activo=TRUE AND estado='fuera_de_servicio')::int equipos_fuera_servicio,(SELECT COUNT(*) FROM mantenimientos WHERE estado IN('programado','pendiente') AND fecha_programada<CURRENT_DATE)::int mantenimientos_vencidos,(SELECT COUNT(*) FROM reportes_fallas WHERE estado NOT IN('cerrada','rechazada'))::int fallas_abiertas,(SELECT COUNT(*) FROM reportes_fallas WHERE prioridad='critica' AND estado NOT IN('cerrada','rechazada'))::int fallas_criticas`);return r.rows[0]},
 async equiposPorEstado(){return (await pool.query('SELECT estado,COUNT(*)::int total FROM equipos WHERE activo=TRUE GROUP BY estado ORDER BY estado')).rows},
 async equiposPorArea(){return (await pool.query(`SELECT COALESCE(u.nombre,'Sin ubicación') area,COUNT(*)::int total FROM equipos e LEFT JOIN ubicaciones u ON u.id=e.ubicacion_id WHERE e.activo=TRUE GROUP BY u.nombre ORDER BY total DESC`)).rows},
 async equiposPorCategoria(){return (await pool.query(`SELECT COALESCE(c.nombre,'Sin categoría') categoria,COUNT(*)::int total FROM equipos e LEFT JOIN categorias_equipos c ON c.id=e.categoria_id WHERE e.activo=TRUE GROUP BY c.nombre ORDER BY total DESC`)).rows},
 async equiposPorRiesgo(){return (await pool.query(`SELECT nivel_riesgo riesgo,COUNT(*)::int total FROM equipos WHERE activo=TRUE GROUP BY nivel_riesgo ORDER BY total DESC`)).rows},
 async fallas(){const resumen=(await pool.query(`SELECT estado,prioridad,COUNT(*)::int total FROM reportes_fallas GROUP BY estado,prioridad ORDER BY estado,prioridad`)).rows;const equipos=(await pool.query(`SELECT e.id,e.nombre,e.codigo_interno,COUNT(f.id)::int total_fallas FROM equipos e JOIN reportes_fallas f ON f.equipo_id=e.id GROUP BY e.id ORDER BY total_fallas DESC LIMIT 10`)).rows;return{resumen,equipos_con_mas_fallas:equipos}},
 async mantenimientos(){const r=await pool.query(`SELECT COUNT(*) FILTER(WHERE estado IN('programado','pendiente') AND fecha_programada BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int proximos,COUNT(*) FILTER(WHERE estado IN('programado','pendiente') AND fecha_programada<CURRENT_DATE)::int vencidos,COUNT(*) FILTER(WHERE estado='completado')::int completados FROM mantenimientos`);return r.rows[0]},
 async costos(){const r=await pool.query(`SELECT COALESCE(SUM(costo),0) costo_total,COALESCE(SUM(costo) FILTER(WHERE fecha_realizacion>=date_trunc('month',CURRENT_DATE)),0) costo_mes,COALESCE(AVG(costo) FILTER(WHERE estado='completado'),0) promedio_mantenimiento FROM mantenimientos`);return r.rows[0]},
};module.exports={dashboardRepository};
