const pool=require('../config/database');const fields=['descripcion','prioridad','evidencia_url','estado','tecnico_asignado_id','solucion','fecha_cierre'];
const {ReporteFalla}=require('../entities/ReporteFalla');
const select=`SELECT f.*,e.codigo_interno,e.nombre AS equipo_nombre,ur.nombre AS reportado_por_nombre,ut.nombre AS tecnico_nombre FROM reportes_fallas f JOIN equipos e ON e.id=f.equipo_id JOIN usuarios ur ON ur.id=f.reportado_por LEFT JOIN usuarios ut ON ut.id=f.tecnico_asignado_id`;
const fallaRepository={
 async findAll({page=1,limit=10,estado,prioridad,equipo_id,tecnico_id,reportado_por}={}){const vals=[],conds=[];for(const [col,val] of [['f.estado',estado],['f.prioridad',prioridad],['f.equipo_id',equipo_id],['f.tecnico_asignado_id',tecnico_id],['f.reportado_por',reportado_por]])if(val){vals.push(val);conds.push(`${col}=$${vals.length}`)}const where=conds.length?`WHERE ${conds.join(' AND ')}`:'';const count=await pool.query(`SELECT COUNT(*) FROM reportes_fallas f ${where}`,vals);vals.push(limit,(page-1)*limit);const r=await pool.query(`${select} ${where} ORDER BY CASE f.prioridad WHEN 'critica' THEN 1 WHEN 'alta' THEN 2 WHEN 'media' THEN 3 ELSE 4 END,f.created_at DESC LIMIT $${vals.length-1} OFFSET $${vals.length}`,vals);return{rows:ReporteFalla.fromRows(r.rows),total:Number(count.rows[0].count)}},
 async findById(id){const r=await pool.query(`${select} WHERE f.id=$1`,[id]);return ReporteFalla.fromRow(r.rows[0])},
 async create(data){const r=await pool.query(`INSERT INTO reportes_fallas(equipo_id,reportado_por,descripcion,prioridad,evidencia_url) VALUES($1,$2,$3,$4,$5) RETURNING id`,[data.equipo_id,data.reportado_por,data.descripcion,data.prioridad||'media',data.evidencia_url||null]);return this.findById(r.rows[0].id)},
 async update(id,data){const entries=Object.entries(data).filter(([k,v])=>fields.includes(k)&&v!==undefined);if(!entries.length)return this.findById(id);const vals=entries.map(([,v])=>v===''?null:v);vals.push(id);await pool.query(`UPDATE reportes_fallas SET ${entries.map(([k],i)=>`${k}=$${i+1}`).join(',')} WHERE id=$${vals.length}`,vals);return this.findById(id)},
};module.exports={fallaRepository};
