const pool=require('../config/database');
const {MovimientoEquipo}=require('../entities/MovimientoEquipo');
const select=`SELECT m.*,e.codigo_interno,e.nombre AS equipo_nombre,uo.nombre AS ubicacion_origen,ud.nombre AS ubicacion_destino,ue.nombre AS responsable_entrega,ur.nombre AS responsable_recibe FROM movimientos_equipos m JOIN equipos e ON e.id=m.equipo_id LEFT JOIN ubicaciones uo ON uo.id=m.ubicacion_origen_id JOIN ubicaciones ud ON ud.id=m.ubicacion_destino_id LEFT JOIN usuarios ue ON ue.id=m.responsable_entrega_id LEFT JOIN usuarios ur ON ur.id=m.responsable_recibe_id`;
const movimientoRepository={
 async findAll({page=1,limit=10,tipo,estado,equipo_id}={}){const vals=[],conds=[];for(const [col,val] of [['m.tipo',tipo],['m.estado',estado],['m.equipo_id',equipo_id]])if(val){vals.push(val);conds.push(`${col}=$${vals.length}`)}const where=conds.length?`WHERE ${conds.join(' AND ')}`:'';const count=await pool.query(`SELECT COUNT(*) FROM movimientos_equipos m ${where}`,vals);vals.push(limit,(page-1)*limit);const r=await pool.query(`${select} ${where} ORDER BY m.fecha_salida DESC LIMIT $${vals.length-1} OFFSET $${vals.length}`,vals);return{rows:MovimientoEquipo.fromRows(r.rows),total:Number(count.rows[0].count)}},
 async findById(id){const r=await pool.query(`${select} WHERE m.id=$1`,[id]);return MovimientoEquipo.fromRow(r.rows[0])},async findByEquipo(id){const r=await pool.query(`${select} WHERE m.equipo_id=$1 ORDER BY m.fecha_salida DESC`,[id]);return MovimientoEquipo.fromRows(r.rows)},async findPrestados(){const r=await pool.query(`${select} WHERE m.tipo='prestamo' AND m.estado='activo' ORDER BY m.fecha_prevista_devolucion`);return MovimientoEquipo.fromRows(r.rows)},
 async findActiveByEquipo(id){const r=await pool.query("SELECT * FROM movimientos_equipos WHERE equipo_id=$1 AND estado='activo'",[id]);return MovimientoEquipo.fromRow(r.rows[0])},
 async create(data){const client=await pool.connect();try{await client.query('BEGIN');const estado=data.tipo==='traslado'?'completado':'activo';const r=await client.query(`INSERT INTO movimientos_equipos(equipo_id,tipo,ubicacion_origen_id,ubicacion_destino_id,responsable_entrega_id,responsable_recibe_id,fecha_salida,fecha_prevista_devolucion,motivo,estado,observaciones,estado_equipo_anterior,created_by) VALUES($1,$2,$3,$4,$5,$6,COALESCE($7,NOW()),$8,$9,$10,$11,$12,$13) RETURNING id`,[data.equipo_id,data.tipo,data.ubicacion_origen_id||null,data.ubicacion_destino_id,data.responsable_entrega_id||null,data.responsable_recibe_id||null,data.fecha_salida||null,data.fecha_prevista_devolucion||null,data.motivo,estado,data.observaciones||null,data.estado_equipo_anterior,data.created_by]);await client.query('UPDATE equipos SET ubicacion_id=$1,estado=$2 WHERE id=$3',[data.ubicacion_destino_id,data.tipo==='prestamo'?'prestado':data.estado_equipo_anterior,data.equipo_id]);await client.query('COMMIT');return this.findById(r.rows[0].id)}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}},
 async devolver(id){const client=await pool.connect();try{await client.query('BEGIN');const m=await client.query("UPDATE movimientos_equipos SET estado='devuelto',fecha_real_devolucion=NOW() WHERE id=$1 AND tipo='prestamo' AND estado='activo' RETURNING *",[id]);if(!m.rows[0]){const e=new Error('NO_ACTIVO');e.code='BUSINESS';throw e}await client.query('UPDATE equipos SET ubicacion_id=$1,estado=COALESCE($2,\'disponible\') WHERE id=$3',[m.rows[0].ubicacion_origen_id,m.rows[0].estado_equipo_anterior,m.rows[0].equipo_id]);await client.query('COMMIT');return this.findById(id)}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}},
};module.exports={movimientoRepository};
